import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar/Navbar"
import Footer from "./Footer/Footer"
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";
import UserProvider from "@/context/userProvider";
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <UserProvider>
        <ToastContainer />
       <Navbar />
        {children}
       <Footer/>
      </UserProvider>
        </body>
    </html>
  );
}
